### ISSUE TITLE
Upscaler mute all the other sounds

### ISSUE THREAD

**Issue by rub3nsdt** [the-database/mpv-upscale-2x_animejanai#12]
Hello, when I play a video with the upscale feature, all other system sounds are muted. I want to talk on Discord while using the program, but when I start the video, I stop hearing it. Is there any way to hear the other programs besides the audio track of the video I'm playing?

**Comment by the-database** [comment]
Delete this line from your mpv.conf: `audio-exclusive = yes`

**Comment by rub3nsdt** [comment]
It has worked, thank you.
