### ISSUE TITLE
Tip regarding nvenc encoding in the bat-files.

### ISSUE THREAD

**Issue by BlankFX1** [the-database/mpv-upscale-2x_animejanai#18]
Instead of 
`set video_settings=hevc_nvenc -preset slow -profile:v main10 -b:v 50M`
use
`set video_settings=hevc_nvenc -preset p7 -profile:v main10 -b:v 50M`
instead.

Also works for h264_nvenc.

You can read more about the more modern nvenc presets here:
https://developer.nvidia.com/blog/introducing-video-codec-sdk-10-presets/

**Comment by the-database** [comment]
Thanks for the tip, I wasn't too familiar with NVENC. This has been merged and will be included in the next release.
