### ISSUE TITLE
Does this only work on nvidia?

### ISSUE THREAD

**Issue by Tendodeku** [the-database/mpv-upscale-2x_animejanai#2]
Does this only work on nvidia?

**Comment by the-database** [comment]
Unfortunately AMD doesn't support TensorRT, so realtime playback isn't possible with AMD. While AMD supports NCNN which could be used, performance is too slow for realtime playback. I tested NCNN and got frame drops in mpv even while using an NVIDIA RTX 4090 with the fastest performing model. 

If we drop the requirement for realtime playback in mpv, it is possible to use the models to render upscaled video to new files. I've added some steps on how to do that.

**Comment by John-Gee** [comment]
Is there nothing usable as part of rocM or HSA?

**Comment by the-database** [comment]
> Is there nothing usable as part of rocM or HSA?

I don't think so, but it seems that DirectML would be an option. It would still be too slow to run the models in realtime on most content but it would allow encoding videos on AMD systems at least.

http://blog.livedoor.jp/hddvddegogo/archives/52228389.html
