### ISSUE TITLE
upscaling of the wire mesh pattern in the background

### ISSUE THREAD

**Issue by animeojisan** [the-database/mpv-upscale-2x_animejanai#21]
The V2 image quality is really really excellent. Thanks for the great work!

However, there are some not-so-good points. I don't think the upscaling of the wire mesh pattern in the background is very good. It occurs at low resolutions of 360-480p. I look forward to improvements in the next version.

![yofukashi-480p-compactx4](https://github.com/the-database/mpv-upscale-2x_animejanai/assets/132756551/5a3805c5-9fe0-4490-be43-7c58d8ec7d7f)

**Comment by animeojisan** [comment]
Thanks for your reply. Yes, I understand.

There are a large number of 480i/p Standard-definition anime. (Only released on DVD)  If possible, please consider developing a model for SD.

**Comment by 422415** [comment]
Don't worry we want to see a AnimeJaNai SD too, but I expect it to be a long way away.

**Comment by animeojisan** [comment]
I'll wait forever for AnimeJaNai SD to come out! Hahaha
