### ISSUE TITLE
Running on Android MPV?

### ISSUE THREAD

**Issue by arianaa30** [the-database/mpv-upscale-2x_animejanai#28]
Is there a way to run these on a phone? Like, loading in android mpv player, etc?

**Comment by the-database** [comment]
Phones aren't be powerful enough to run this anytime soon. These currently require a mid- or high-end NVIDIA desktop/laptop GPU as seen in the benchmarks: https://github.com/the-database/mpv-upscale-2x_animejanai/wiki/Benchmarks

**Comment by arianaa30** [comment]
Isn't it like anime4k shaders that could be run in android mpv? Or these are GAN models?
