### ISSUE TITLE
Do you plan to release the missing SuperUltraCompact models?

### ISSUE THREAD

**Issue by monarc99** [the-database/mpv-upscale-2x_animejanai#3]
I use 2x_AnimeJaNai_ Strong_V1_ SuperUltraCompact_net_g_100000 on my 1060 GTX card to upsacle sd material to fullhd.

It would be nice to have the normal and soft variant of the model. Do you plan to train and release them?

**Comment by the-database** [comment]
I'm currently working on V2 models to address some of the shortcomings of the V1 models. I think V2 will provide what you're looking for in a Soft model. Please see #5 which includes some sample screenshots of progress on the new models.

**Comment by hooke007** [comment]
Hello, @the-database . I found the model-file size in tag 1.0.1 is different from 1.0.0, and two of them are missing. Is there any reason and improvement?
