### ISSUE TITLE
GLSL Shader lite version

### ISSUE THREAD

**Issue by NeilTohno** [the-database/mpv-upscale-2x_animejanai#32]
Hi there,

Setting up animejanai v3 on a system with AMD Radeon graphics can be challenging, especially for noobie. 
I'd like to request a lite version of animejanai v3 implemented as a GLSL shader for mpv player.

This would allow users easily use animejanai.

Example, 
https://github.com/igv/FSRCNN-TensorFlow/releases/tag/1.1

Thank you.

**Comment by hooke007** [comment]
I don't think mpv's shader system is strong&easy enough to implement this feature. FSRCNNX is too tiny to be refered.

You can also check the dev of anime4k's opinion. https://github.com/bloc97/Anime4K/issues/145#issuecomment-1509999595 (Which blocks the next gen of a4k)

**Comment by NeilTohno** [comment]
> I don't think mpv's shader system is strong&easy enough to implement this feature. FSRCNNX is too tiny to be refered.
> 
> You can also check the dev of anime4k's opinion. [bloc97/Anime4K#145 (comment)](https://github.com/bloc97/Anime4K/issues/145#issuecomment-1509999595) (Which blocks the next gen of a4k)

大兄弟，咱要求的是 lite 版本而已，又不是完全版本，
看作者考虑了，谢过

**Comment by hooke007** [comment]
> 咱要求的是 lite 版本而已，又不是完全版本

srvggnet 本身就是 esrgan 的lite版本了
