### ISSUE TITLE
save-position-on-quit not working

### ISSUE THREAD

**Issue by hiddenz08** [the-database/mpv-upscale-2x_animejanai#33]
When I press close the player and then open again it starts from the begining instead of where It was before. The option save-position-on-quit is set to yes on the config but it's not working properly

**Comment by mcabel** [comment]
same here. I tried launching with --save-position-on-quit and editing the conf file, but neither worked. 
I'm using version 3 on windows 11, the portable version. (idk if it's the same for the poster above ).

**Comment by the-database** [comment]
In `mpv.conf`, if you see `watch-later-options-clr`, change it to `watch-later-options=start`. If `watch-later-options-clr` isn't there, just add `watch-later-options=start` to the conf.

**Comment by mcabel** [comment]
> watch-later-options=start

this solves the issue for me, thanks.

**Comment by the-database** [comment]
Fixed in v3.1.0
