### ISSUE TITLE
[Request] Add Intel and AMD support (documentation)

### ISSUE THREAD

**Issue by Aseiel** [the-database/mpv-upscale-2x_animejanai#34]
Please add:
- documentation for usage on Intel and AMD with DirectML (change to DirectML in global settings).
- fp32 models as only those are working with DirectML.
- V2 models as those are preferable for some video sources
- fp32 SD model 

It works fine on my Intel Arc A750.
Thank You for Your hard work :)

**Comment by the-database** [comment]
This is now documented here: https://github.com/the-database/mpv-upscale-2x_animejanai/wiki/Setup-for-AMD-or-Intel-Arc-users
